package Proyectofinahotel71.vistas;






import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

public class MenuPrincipal extends javax.swing.JFrame {

    
    
    
   
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ingresoHuesped = new javax.swing.JMenu();
        opingresoHuesped = new javax.swing.JMenuItem();
        reservaHuesped = new javax.swing.JMenu();
        opreservaHuesped = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GRAN HOTEL IDEAL -  MENU PRINCIPAL");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1089, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );

        ingresoHuesped.setText("HUESPEDES");
        ingresoHuesped.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        opingresoHuesped.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        opingresoHuesped.setText("Ingreso Huesped");
        opingresoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opingresoHuespedActionPerformed(evt);
            }
        });
        ingresoHuesped.add(opingresoHuesped);

        jMenuBar1.add(ingresoHuesped);

        reservaHuesped.setText("RESERVAS");
        reservaHuesped.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        opreservaHuesped.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        opreservaHuesped.setText("Formulario de Reservas");
        opreservaHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opreservaHuespedActionPerformed(evt);
            }
        });
        reservaHuesped.add(opreservaHuesped);

        jMenuBar1.add(reservaHuesped);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void opingresoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opingresoHuespedActionPerformed
        // TODO add your handling code here:
        
       ingresoHuesped verventana = new ingresoHuesped();
        escritorio.add(verventana);
                 verventana.show();
        
    }//GEN-LAST:event_opingresoHuespedActionPerformed

    private void opreservaHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opreservaHuespedActionPerformed
        // TODO add your handling code here:
        
         reservaHuesped verventana = new reservaHuesped();
        escritorio.add(verventana);
                 verventana.show();
        
    }//GEN-LAST:event_opreservaHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(new MetalLookAndFeel());
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                new MenuPrincipal() .setVisible(true);
                
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu ingresoHuesped;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opingresoHuesped;
    private javax.swing.JMenuItem opreservaHuesped;
    private javax.swing.JMenu reservaHuesped;
    // End of variables declaration//GEN-END:variables
}
